server:
  port: 8080
spring:
  application:
    name: banking-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/TESTHTC}
    username: ${DB_USER:root}
    password: ${DB_PASS:Admin123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
    show-sql: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html